-- AlterEnum
ALTER TYPE "booking_type" ADD VALUE IF NOT EXISTS 'POINT_TO_POINT';
ALTER TYPE "booking_type" ADD VALUE IF NOT EXISTS 'DAILY';
ALTER TYPE "booking_type" ADD VALUE IF NOT EXISTS 'WEEKLY';
ALTER TYPE "booking_type" ADD VALUE IF NOT EXISTS 'MONTHLY';

-- AlterTable
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "hire_duration_minutes" INTEGER;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "hire_start_at" TIMESTAMPTZ(6);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "hire_end_at" TIMESTAMPTZ(6);
