/**
 * Phase 51 — Enhanced Offers, Coupons, Gift Boxes & Scratch Cards Catalog
 * Supporting Customer & Driver Personas with Images and Locked State Terms & Conditions.
 */

export type OfferCategory = 'DISCOUNT' | 'GIFT_BOX' | 'SCRATCH_CARD';
export type TargetPersona = 'CUSTOMER' | 'DRIVER' | 'BOTH';

export interface EnhancedOfferItem {
  id: string;
  code: string | null;
  name: string;
  tagline: string;
  description: string;
  category: OfferCategory;
  image: string; // Public folder image path
  targetPersona: TargetPersona;
  discountType: 'PERCENTAGE' | 'FLAT' | 'CASHBACK' | 'REWARD_POINTS';
  discountValue: string;
  maxDiscountAmount?: string | null;
  minBookingValue?: string | null;
  isLocked: boolean;
  lockReason: string;
  unlockProgressPercent: number; // 0 to 100
  unlockRequirement: string;
  termsAndConditions: string[];
  isExpired: boolean;
  endsAt: string | null;
  badgeText?: string;
}

export const CUSTOMER_OFFERS_CATALOG: EnhancedOfferItem[] = [
  {
    id: 'cust_off_1',
    code: 'WELCOME50',
    name: '50% OFF First Chauffeur Ride',
    tagline: 'Welcome Bonus for New Customers',
    description:
      'Get 50% discount up to ₹300 on your first hourly or outstation chauffeur booking with Get Apna Driver.',
    category: 'DISCOUNT',
    image: '/DiscountImg.png',
    targetPersona: 'CUSTOMER',
    discountType: 'PERCENTAGE',
    discountValue: '50% OFF',
    maxDiscountAmount: '₹300',
    minBookingValue: '₹499',
    isLocked: false,
    lockReason: 'Unlocked & ready for first ride',
    unlockProgressPercent: 100,
    unlockRequirement: 'First Ride Unlocked',
    termsAndConditions: [
      'Valid strictly for first-time Get Apna Driver customers.',
      'Maximum discount capped at ₹300 per booking.',
      'Minimum booking fare requirement of ₹499 applies.',
      'Cannot be combined with any other promotional coupon or referral credits.',
      'Subject to chauffeur availability in Delhi NCR, Mumbai, and Bengaluru.',
    ],
    isExpired: false,
    endsAt: '2026-12-31T23:59:59Z',
    badgeText: 'FIRST RIDE',
  },
  {
    id: 'cust_off_2',
    code: 'OUTSTATION250',
    name: '₹250 Flat Discount on Outstation Trips',
    tagline: 'Save Big on Weekend Getaways',
    description:
      'Enjoy ₹250 instant cashback on outstation round trips over 100 km with verified professional drivers.',
    category: 'DISCOUNT',
    image: '/DiscountImg1.png',
    targetPersona: 'CUSTOMER',
    discountType: 'FLAT',
    discountValue: '₹250 OFF',
    maxDiscountAmount: '₹250',
    minBookingValue: '₹1,499',
    isLocked: true,
    lockReason: 'Complete 2 local city rides to unlock outstation coupon',
    unlockProgressPercent: 50,
    unlockRequirement: '1 / 2 City Rides Completed',
    termsAndConditions: [
      'Coupon unlocks automatically after completing 2 city hourly bookings.',
      'Applicable only on outstation multi-day or round-trip bookings.',
      'Minimum booking value of ₹1,499 required.',
      'Toll taxes, state permits, and driver night allowances are charged separately.',
      'Offer non-transferable and non-refundable against cash.',
    ],
    isExpired: false,
    endsAt: '2026-11-30T23:59:59Z',
    badgeText: 'LOCKED',
  },
  {
    id: 'cust_off_3',
    code: 'FESTIVEGIFT',
    name: 'Festive Season VIP Gift Box',
    tagline: 'Surprise Rewards & Free Ride Upgrades',
    description:
      'Unlock special festive vouchers, airport lounge access passes, and complimentary extension hours.',
    category: 'GIFT_BOX',
    image: '/GiftBox.png',
    targetPersona: 'CUSTOMER',
    discountType: 'CASHBACK',
    discountValue: 'Surprise Box',
    maxDiscountAmount: '₹1,000 Value',
    minBookingValue: '₹999',
    isLocked: true,
    lockReason: 'Complete 3 bookings in a single calendar month to open Gift Box',
    unlockProgressPercent: 66,
    unlockRequirement: '2 / 3 Monthly Rides Completed',
    termsAndConditions: [
      'Gift box contains randomized rewards worth between ₹200 and ₹1,000.',
      'Requires minimum 3 completed rides in the current calendar month.',
      'Vouchers inside the gift box must be redeemed within 30 days of opening.',
      'Platform reserves right to substitute gift box contents based on availability.',
    ],
    isExpired: false,
    endsAt: '2026-10-31T23:59:59Z',
    badgeText: 'LOCKED GIFT BOX',
  },
  {
    id: 'cust_off_4',
    code: 'VIPCLUB500',
    name: 'VIP Club Royal Gift Box',
    tagline: 'Luxury Chauffeur Service Reward',
    description:
      'Exclusive luxury gift hamper for top 5% premium customers with free driver wait-time waiver.',
    category: 'GIFT_BOX',
    image: '/GiftBox1.png',
    targetPersona: 'CUSTOMER',
    discountType: 'REWARD_POINTS',
    discountValue: '500 VIP Pts',
    maxDiscountAmount: '₹500 Value',
    minBookingValue: '₹1,999',
    isLocked: true,
    lockReason: 'Achieve VIP Gold Status or complete 10 lifetime rides',
    unlockProgressPercent: 70,
    unlockRequirement: '7 / 10 Lifetime Rides Completed',
    termsAndConditions: [
      'Exclusive to users with verified VIP Gold status or 10+ completed bookings.',
      'Includes 60 minutes free wait-time credit on Luxury Sedan bookings.',
      'Points automatically credit to customer wallet upon unlocking.',
      'Subject to VIP Club terms of membership and fair usage guidelines.',
    ],
    isExpired: false,
    endsAt: '2026-12-15T23:59:59Z',
    badgeText: 'VIP LOCKED',
  },
  {
    id: 'cust_off_5',
    code: 'LUCKYCARD100',
    name: 'Weekly Lucky Ride Scratch Card',
    tagline: 'Scratch & Win Up to ₹1,000 Cashback',
    description:
      'Every completed ride earns a digital scratch card. Reveal instant wallet credits or ride discounts.',
    category: 'SCRATCH_CARD',
    image: '/scratchCard.png',
    targetPersona: 'CUSTOMER',
    discountType: 'CASHBACK',
    discountValue: 'Up to ₹1,000',
    maxDiscountAmount: '₹1,000',
    minBookingValue: '₹399',
    isLocked: true,
    lockReason: 'Scratch card unlocks immediately after completing your next ride',
    unlockProgressPercent: 0,
    unlockRequirement: 'Complete 1 Ride to Scratch',
    termsAndConditions: [
      'One scratch card issued per eligible completed booking above ₹399.',
      'Winnings are credited directly to Get Apna Driver Customer Wallet.',
      'Scratch cards expire if not scratched within 7 days of issue.',
      'Cancelled rides disqualify scratch card issuance.',
    ],
    isExpired: false,
    endsAt: '2026-12-31T23:59:59Z',
    badgeText: 'SCRATCH & WIN',
  },
  {
    id: 'cust_off_6',
    code: 'MEGASCRATCH',
    name: 'Mega Airport Transfer Scratch Card',
    tagline: 'Guaranteed Cashback on Airport Trips',
    description: 'Guaranteed minimum ₹150 up to ₹500 cashback for airport drop & pickup bookings.',
    category: 'SCRATCH_CARD',
    image: '/ScratchCard1.png',
    targetPersona: 'CUSTOMER',
    discountType: 'FLAT',
    discountValue: '₹150 – ₹500',
    maxDiscountAmount: '₹500',
    minBookingValue: '₹799',
    isLocked: true,
    lockReason: 'Book an Airport Duty Chauffeur to unlock Mega Scratch Card',
    unlockProgressPercent: 0,
    unlockRequirement: 'Book 1 Airport Ride',
    termsAndConditions: [
      'Guaranteed cashback of at least ₹150 for all completed airport transfers.',
      'Scratch card must be revealed in app within 48 hours of ride completion.',
      'Valid across all terminal pickup and drop points.',
      'Disputes regarding cashback amounts subject to customer support verification.',
    ],
    isExpired: false,
    endsAt: '2026-11-15T23:59:59Z',
    badgeText: 'AIRPORT SPECIAL',
  },
];

export const DRIVER_OFFERS_CATALOG: EnhancedOfferItem[] = [
  {
    id: 'drv_off_1',
    code: 'PEAKBONUS500',
    name: 'Peak Hours ₹500 Chauffeur Bonus',
    tagline: 'Earn Extra During High Demand Shifts',
    description:
      'Complete 4 peak-hour trips between 5 PM and 10 PM to earn ₹500 direct incentive payout.',
    category: 'DISCOUNT',
    image: '/DiscountImg.png',
    targetPersona: 'DRIVER',
    discountType: 'FLAT',
    discountValue: '₹500 Bonus',
    maxDiscountAmount: '₹500',
    minBookingValue: '₹400',
    isLocked: false,
    lockReason: 'Currently Active Shift Challenge',
    unlockProgressPercent: 100,
    unlockRequirement: 'Unlocked & Active Today',
    termsAndConditions: [
      'Requires completing 4 peak-hour trips in a single evening shift (5 PM – 10 PM).',
      'Acceptance rate during shift must remain above 90%.',
      'Zero driver-initiated cancellations allowed during the active campaign period.',
      'Incentive credited directly to Driver Wallet at end of shift reconciliation.',
    ],
    isExpired: false,
    endsAt: '2026-12-31T23:59:59Z',
    badgeText: 'SHIFT BONUS',
  },
  {
    id: 'drv_off_2',
    code: 'FUELCARD250',
    name: '₹250 Weekly Fuel & Maintenance Subsidy',
    tagline: 'Partner Convenience & Fuel Relief',
    description:
      'Get ₹250 weekly fuel voucher on maintaining a 100% trip completion record over 5 consecutive days.',
    category: 'DISCOUNT',
    image: '/DiscountImg1.png',
    targetPersona: 'DRIVER',
    discountType: 'FLAT',
    discountValue: '₹250 Subsidy',
    maxDiscountAmount: '₹250',
    minBookingValue: 'N/A',
    isLocked: true,
    lockReason: 'Complete 15 rides in 5 days with zero cancellations to unlock',
    unlockProgressPercent: 60,
    unlockRequirement: '9 / 15 Weekly Trips Completed',
    termsAndConditions: [
      'Driver must complete at least 15 trips in 5 consecutive working days.',
      'Maintain overall weekly rating of 4.75 stars or higher.',
      'Fuel coupon code can be redeemed at participating partner petrol stations.',
      'Fraudulent trip manipulation or fake GPS telemetry will lead to permanent disqualification.',
    ],
    isExpired: false,
    endsAt: '2026-11-30T23:59:59Z',
    badgeText: 'LOCKED SUBSIDY',
  },
  {
    id: 'drv_off_3',
    code: 'TOPDRIVERGIFT',
    name: 'Star Chauffeur Monthly Reward Box',
    tagline: 'Recognizing Excellence on the Road',
    description:
      'Exclusive gift hamper containing premium uniform kit, car grooming vouchers, and ₹1,500 bonus.',
    category: 'GIFT_BOX',
    image: '/GiftBox.png',
    targetPersona: 'DRIVER',
    discountType: 'CASHBACK',
    discountValue: '₹1,500 Box',
    maxDiscountAmount: '₹1,500',
    minBookingValue: 'N/A',
    isLocked: true,
    lockReason: 'Achieve 4.9★ rating with 30+ completed trips this month',
    unlockProgressPercent: 75,
    unlockRequirement: '23 / 30 Monthly Trips (4.9★ Required)',
    termsAndConditions: [
      'Awarded to top 10% drivers in each operating zone based on customer ratings.',
      'Minimum of 30 completed rides required in the active calendar month.',
      'Requires 100% compliance record on uniform and identity verification.',
      'Gift box items dispatched or credited within 3 working days of month end.',
    ],
    isExpired: false,
    endsAt: '2026-10-31T23:59:59Z',
    badgeText: 'STAR CHAUFFEUR',
  },
  {
    id: 'drv_off_4',
    code: 'MILESTONE500',
    name: '500 Trips Legend Gift Box',
    tagline: 'Career Milestone Celebration Reward',
    description:
      'Lifetime achievement reward box with ₹2,500 cash reward, gold badge badge, and priority dispatch tier.',
    category: 'GIFT_BOX',
    image: '/GiftBox1.png',
    targetPersona: 'DRIVER',
    discountType: 'FLAT',
    discountValue: '₹2,500 Bonus',
    maxDiscountAmount: '₹2,500',
    minBookingValue: 'N/A',
    isLocked: true,
    lockReason: 'Complete 500 lifetime completed trips on Get Apna Driver',
    unlockProgressPercent: 84,
    unlockRequirement: '420 / 500 Lifetime Trips Completed',
    termsAndConditions: [
      'Applicable upon completing 500 total trips on the platform.',
      'Permanently upgrades driver profile to Gold Priority Dispatch Tier.',
      'Cash bonus ₹2,500 transferred directly to linked bank account.',
      'All lifetime rides must satisfy safety and non-fraudulent audit criteria.',
    ],
    isExpired: false,
    endsAt: '2026-12-31T23:59:59Z',
    badgeText: 'MILESTONE LOCKED',
  },
  {
    id: 'drv_off_5',
    code: 'ZEROCANCELSTREAK',
    name: 'Zero-Cancellation Weekly Scratch Card',
    tagline: 'Reliability Reward Scratch Card',
    description:
      'Scratch card with guaranteed reward between ₹200 and ₹750 for maintaining 0% cancellation rate.',
    category: 'SCRATCH_CARD',
    image: '/scratchCard.png',
    targetPersona: 'DRIVER',
    discountType: 'CASHBACK',
    discountValue: 'Up to ₹750',
    maxDiscountAmount: '₹750',
    minBookingValue: 'N/A',
    isLocked: true,
    lockReason: 'Complete 10 consecutive accepted trips with 0 cancellations',
    unlockProgressPercent: 70,
    unlockRequirement: '7 / 10 Trips (0 Cancellations)',
    termsAndConditions: [
      'Issued weekly to drivers with 0% cancellation rate over 10 consecutive assigned trips.',
      'Guaranteed minimum reward of ₹200 credited to driver ledger upon scratching.',
      'Scratch card must be revealed within 5 days of release.',
    ],
    isExpired: false,
    endsAt: '2026-12-31T23:59:59Z',
    badgeText: 'RELIABILITY CARD',
  },
  {
    id: 'drv_off_6',
    code: 'PROSTREAKCARD',
    name: 'Pro Chauffeur Weekend Scratch Card',
    tagline: 'Weekend High-Volume Payout',
    description:
      'Exclusive weekend scratch card unlocking up to ₹1,200 for completing 8 Friday-to-Sunday shifts.',
    category: 'SCRATCH_CARD',
    image: '/ScratchCard1.png',
    targetPersona: 'DRIVER',
    discountType: 'CASHBACK',
    discountValue: 'Up to ₹1,200',
    maxDiscountAmount: '₹1,200',
    minBookingValue: 'N/A',
    isLocked: true,
    lockReason: 'Complete 8 weekend shifts (Friday to Sunday) to unlock',
    unlockProgressPercent: 50,
    unlockRequirement: '4 / 8 Weekend Shifts Completed',
    termsAndConditions: [
      'Valid only for completed trips between Friday 4 PM and Sunday 11:59 PM.',
      'Requires a minimum of 8 completed weekend shifts.',
      'Scratch card reward value ranges from ₹300 to ₹1,200 based on streak tier.',
      'Fair usage and safety compliance policies strictly enforced.',
    ],
    isExpired: false,
    endsAt: '2026-11-30T23:59:59Z',
    badgeText: 'WEEKEND PRO',
  },
];
