import { SYSTEM_ROLE_CODES, type SystemRoleCode } from './role-catalog';
import { PERMISSIONS, type PermissionCode } from './permission-catalog';

/**
 * Least-privilege role -> permission mapping used to seed `role_permissions`.
 * CUSTOMER and DRIVER never receive administrative permissions; ADMINISTRATOR
 * permissions are intentionally enumerated rather than granted via a
 * bypass/wildcard, so authorization checks stay uniform and testable.
 */
export const ROLE_PERMISSION_MAP: Record<SystemRoleCode, readonly PermissionCode[]> = {
  [SYSTEM_ROLE_CODES.CUSTOMER]: [
    PERMISSIONS.USERS_PROFILE_READ,
    PERMISSIONS.USERS_PROFILE_UPDATE,
    PERMISSIONS.LOCATION_NEARBY_READ,
    PERMISSIONS.BOOKINGS_READ,
    PERMISSIONS.BOOKINGS_CREATE,
    PERMISSIONS.BOOKINGS_CANCEL,
    PERMISSIONS.BOOKINGS_TRACK_LOCATION,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  [SYSTEM_ROLE_CODES.DRIVER]: [
    PERMISSIONS.USERS_PROFILE_READ,
    PERMISSIONS.USERS_PROFILE_UPDATE,
    PERMISSIONS.DRIVER_PROFILE_MANAGE,
    PERMISSIONS.DRIVER_DOCUMENT_UPLOAD,
    PERMISSIONS.DRIVER_DOCUMENT_READ_OWN,
    PERMISSIONS.DRIVER_AVAILABILITY_MANAGE,
    PERMISSIONS.LOCATION_DRIVER_UPDATE,
    PERMISSIONS.BOOKINGS_READ,
    PERMISSIONS.DRIVER_ASSIGNMENT_RESPOND,
    PERMISSIONS.DRIVER_JOURNEY_MANAGE,
    PERMISSIONS.BOOKINGS_TRACK_LOCATION,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.FINANCE_WALLET_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
  [SYSTEM_ROLE_CODES.ADMINISTRATOR]: Object.values(PERMISSIONS),
};
